@layout('admin::layouts.navi')

@section('subnav')
    <?php 
        $url = URL::base();
        print '<div class="span2"> <ul class="nav nav-pills nav-stacked">';      
    ?>
@endsection

@section('content')
  <div class="span9">
        @if(Session::get('alert'))
            <?php 
                // Fetch alert
                $alert = Session::get('alert'); 
                // Print Alert message
                print '<div class="alert alert-success">The '.$alert['event'].' was '.$alert['state'].'</div>';
            ?>
        @endif
        <div class="hero-unit">
				<h2>Why this Project comes alive...</h2>
				<p>
					I made it to learn howto handle MVCs and Frameswork, <br />	
					in this Project you will find an dynamicly generated MVC-CMS! <br />
					Nearly everything you see will be generated by the Laravel - "System" <br />
					with data from a Database. <br />
					<br />
					Now I wanna add: <br />
					- Media Support <br />
					- PIM Application. <br />
					- a lot bugfixes <br />
					- and a lot more...
				</p>
				<?php 
                    print '<br /><br /><br />';
                    echo Typography::error('Dj Kazek - big Beat Producer!');
                    echo Typography::warning('Paolo will show Mini Bartagam`s!');
                    echo Typography::info('David let`s QuadroCopter`s rock`s on Laravel Web Project`s! xD');

                ?>
	
            <br /><br /><br /><br />

			<p>Install Migrations - add Database</p>
			<pre>
				<br />	php artisan migrate:install
				<br />	php artisan migrate
			</pre>
			
			<p>Add Table to Admin Bundle</p>
			<pre>
				<br />  php artisan migrate:make admin::create_admins_table
			</pre>

			<P>Publish publish data of Bundles</p>
			<pre>
				<br />  php artisan bundle:publish 
				<br />  php artisan bundle:publish application
			</pre>		
        </div>

@endsection

